### ISSUE TITLE
Possible Decal Issue

### ISSUE THREAD

**Issue by skrubzilla** [iLLeniumStudios/fivem-appearance#128] opened 2022-07-05 14:13 UTC
I don't have much to share other than the fact that for some reason some people see decals on other players and some don't. If they change their outfit it fixes this I have some photos of decals just on people I have seen that I know are not there but that really does not help you much :D

**Comment by TheiLLeniumStudios** [comment] 2022-07-05 20:32
@skrubzilla This is a weird issue. To be honest, the thing is that I can't control what others see because its up to GTA to handle that. If some people are not seeing decals on others then its GTA to be blamed.

**Comment by TheiLLeniumStudios** [comment] 2022-08-16 14:39
Couldn't reproduce. Closing

**Closed by TheiLLeniumStudios** 2022-08-16 14:39 UTC
Labels: invalid, question
