### ISSUE TITLE
Safe no underhair drawebles textures

### ISSUE THREAD

**Issue by TweakyGaming** [iLLeniumStudios/fivem-appearance#5] opened 2022-05-01 07:30 UTC
[![image](https://user-images.githubusercontent.com/80688445/166136582-4dd32c43-24c5-40db-8a3d-73b9addaca0a.png)](https://i.imgur.com/ECMczF5.png)

Save no underhair drawebles textures

like this
https://i.imgur.com/Z7YJusY.jpeg

**Comment by TheiLLeniumStudios** [comment] 2022-05-01 11:38
Kind of duplicate of #3 since the faded hair are applied as tattoos, so I'll have to look into fixing this issue

**Comment by TweakyGaming** [comment] 2022-05-01 12:25
That would be really great if that would work. I find without that always looks so stupid. That was one reason why I use this script. Is only a detail but was glad that this problem has taken someone.

**Comment by TheiLLeniumStudios** [comment] 2022-05-02 08:15
@TweakyGaming Fixed by https://github.com/iLLeniumStudios/fivem-appearance/commit/b69b413312adc7888f1d2cc66782bf32ba56058e

Please get the latest version and let me know if it works for you. Feel free to re-open if there are still issues

**Closed** 2022-05-02 08:20 UTC
Labels: bug
