### ISSUE TITLE
BUG:  /reloadskin - Recharges health | sets health to level when command was used

### ISSUE THREAD

**Issue by dennrick** [iLLeniumStudios/fivem-appearance#37] opened 2022-05-13 01:07 UTC
Issue:  When using the /reloadskin command the players health is restored to the level it was when the command was used.  However, it also freezes that players health at that level.  It automatically restores players health to the level it sets when running the command when they take damage.

Steps to reproduce:

1. Player runs /reloadskin with any amount of health (saying 50% just to put a number)
2. Player is set back to 50% health
3. Player takes damage
4. Players health is rergenerated to 50%
5. Rinse and repeat

**Comment by TheiLLeniumStudios** [comment] 2022-05-13 05:23
Hi @dennrick . Thank you for reporting the issue. It has been fixed with #41 . You can download the resource again from the main branch, or wait until a proper release has been created which includes the fix

**Comment by TheiLLeniumStudios** [comment] 2022-05-13 06:02
Now supported in [v3.2.1](https://github.com/iLLeniumStudios/fivem-appearance/releases/v3.2.1)

**Comment by dennrick** [comment] 2022-05-30 19:13
This is still happening with the latest versions.

**Comment by waseem-h** [comment] 2022-05-30 19:14
@dennrick I will check this again. Thanks for reporting

**Comment by dennrick** [comment] 2022-05-30 19:20
> @dennrick I will check this again. Thanks for reporting

Still doing some more testing myself and this may actually be a bug with qb-ambulancejob. Will test some more and report back.

**Comment by waseem-h** [comment] 2022-05-30 19:22
> > @dennrick I will check this again. Thanks for reporting
> 
> Still doing some more testing myself and this may actually be a bug with qb-ambulancejob. Will test some more and report back.

yeah I was thinking about it. reloadskin changes the PlayerPedId(). So it might be that ambulancejob is using the old object returned from PlayerPedId()

**Comment by TheiLLeniumStudios** [comment] 2022-06-14 19:07
@dennrick Could you try the latest resource from `main` branch and see if the issue is fixed? I've tried to fix it but couldn't test it properly

**Comment by dennrick** [comment] 2022-06-14 19:15
> @dennrick Could you try the latest resource from `main` branch and see if the issue is fixed? I've tried to fix it but couldn't test it properly

Yep will test momentarily.

**Comment by dennrick** [comment] 2022-06-14 19:51
Okay so with the latest main branch we are spawning in on my test server with 50% health and then when you take damage it restores automatically to 25% health.  A revive or bandage useage won't take you above 50% health.

So the regen is still there and health seems to be capped at 50% now.

**Comment by TheiLLeniumStudios** [comment] 2022-06-19 20:08
@dennrick If you're available, could you try again please? I pushed a few changes on main to fix it

**Comment by TheiLLeniumStudios** [comment] 2022-06-19 21:45
Fixed in v3.8.3

**Closed by TheiLLeniumStudios** 2022-06-19 21:45 UTC
Labels: bug
